#!/bin/bash

right=0

for i in 0 1 2 3 4 5 6 7 8 9
do  
  ./MyProg 1> txt/"$i"_test_out.txt 2> txt/Errors.txt < txt/"$i"_test_in.txt
  echo "Test #$i"
  echo "Programm answer: "
  cat txt/"$i"_test_out.txt
  echo "Right answer: "
  cat txt/"$i"_test_res.txt
  echo ""
  if cmp txt/"$i"_test_out.txt txt/"$i"_test_res.txt
  then
    let "right++"
  fi
done

echo "Done right $right task out of 10"
